blog/urls.py
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import MailingCreateView, ClientCreateView, ClientListView, \
    ClientUpdateView, ClientDeleteView, MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailingListView, MailingUpdateView, MailingDeleteView, MailingDetailView, toggle_mailing_activity, LogListView, home

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(home), name='home'),

    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('update_mailing/<int:pk>/', MailingUpdateView.as_view(), name='update_mailing'),
    path('delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('launch_mailing/<int:pk>/', toggle_mailing_activity, name='launch_mailing'),

    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('log_list/', LogListView.as_view(), name='log_list'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, AuthView, ProfileView, EmailVerify, generate_new_password, UserListView, \
    toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('', AuthView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity')
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name='контактный email', unique=True)
    name = models.CharField(max_length=100, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий')
    creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='cоздатель', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=200, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='cоздатель', **NULLABLE)

    def __str__(self):
        return self.body

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Mailing(models.Model):
    EVERY_DAY = 'every_day'
    EVERY_WEEK = 'every_week'
    EVERY_MONTH = 'every_month'

    FREQUENCY_TYPES = (
        (EVERY_DAY, 'раз в день'),
        (EVERY_WEEK, 'раз в неделю'),
        (EVERY_MONTH, 'раз в месяц'),
    )

    COMPLETED = 'completed'
    CREATED = 'created'
    LAUNCHED = 'launched'

    STATUS_TYPES = (
        (COMPLETED, 'завершена'),
        (CREATED, 'создана'),
        (LAUNCHED, 'запущена'),
    )

    mailing_duration = models.TimeField(verbose_name='время рассылки')
    frequency = models.CharField(max_length=11, choices=FREQUENCY_TYPES, verbose_name='периодичность')
    mailing_status = models.CharField(
        max_length=9, choices=STATUS_TYPES, default=CREATED, verbose_name='статус рассылки'
    )
    client = models.ManyToManyField(Client, verbose_name='клиент')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение', **NULLABLE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='cоздатель', **NULLABLE)

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('id',)


class Log(models.Model):

    SENT = 'sent'
    FAILED = 'failed'
    PENDING = 'pending'

    STATUS_CHOICES = (
        (SENT, 'Отправлено'),
        (FAILED, 'Не удалось отправить'),
        (PENDING, 'В ожидании')
    )

    creation_time = models.TimeField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    attempt_date_time = models.DateTimeField(
        auto_now_add=True, verbose_name='дата и время последней попытки', **NULLABLE
    )
    attempt_status = models.CharField(
        max_length=10, verbose_name='статус попытки', choices=STATUS_CHOICES, default=PENDING
    )
    response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE)

    class Meta:
        verbose_name = 'лог рассылки'
        verbose_name_plural = 'логи рассылки'

mailing/forms.py
from django import forms

from mailing.models import Mailing, Message, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        exclude = ('creator',)


class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        exclude = ('creator',)


class MailingForm(StyleFormMixin, forms.ModelForm):

    client = forms.ModelMultipleChoiceField(
        queryset=Client.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label='Клиенты'
    )

    class Meta:
        model = Mailing
        exclude = ('mailing_status', 'creator',)

mailing/views.py
import random

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from mailing.forms import MailingForm, MessageForm, ClientForm
from mailing.models import Message, Mailing, Client, Log


def home(request):

    blog_list = Blog.objects.all()
    blog_list = list(blog_list)
    random.shuffle(blog_list)

    context = {
        'title': 'Главная',
        'mailings': len(Mailing.objects.all()),
        'mailings_is_active': len(Mailing.objects.filter(mailing_status='launched')),
        'unique_clients_count': Client.objects.values('email').count(),
        'random_blog_list': blog_list
    }

    return render(request, 'mailing/home.html', context)


class ClientListView(ListView):
    model = Client

    def get_queryset(self):
        if self.request.user.is_staff:
            return Client.objects.all()
        else:
            return Client.objects.filter(creator=self.request.user.pk)


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        message = form.save()
        message.creator = self.request.user
        message.save()
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator == self.request.user:
            return self.object
        elif self.request.user.is_staff:
            return self.object
        else:
            return None


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator == self.request.user:
            return self.object
        else:
            return None


class MessageListView(ListView):
    model = Message

    def get_queryset(self):
        if self.request.user.is_staff:
            return Message.objects.all()
        else:
            return Message.objects.filter(creator=self.request.user.pk)


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        message = form.save()
        message.creator = self.request.user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator == self.request.user:
            return self.object
        elif self.request.user.is_staff:
            return self.object
        else:
            return None


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator == self.request.user:
            return self.object
        else:
            return None


class MailingListView(ListView):
    model = Mailing

    def get_queryset(self):
        if self.request.user.is_staff:
            return Mailing.objects.all()
        else:
            return Mailing.objects.filter(creator=self.request.user.pk)


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        mailing = form.save()
        mailing.creator = self.request.user
        mailing.save()
        return super().form_valid(form)


class MailingDetailView(DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator == self.request.user:
            return self.object
        elif self.request.user.is_staff:
            return self.object
        else:
            return None


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:mailing_detail', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator == self.request.user:
            return self.object
        elif self.request.user.is_staff:
            return self.object
        else:
            return None


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.creator == self.request.user:
            return self.object
        else:
            return None


def toggle_mailing_activity(request, pk):
    mailing_item = get_object_or_404(Mailing, pk=pk)

    if mailing_item.mailing_status == 'created' or mailing_item.mailing_status == 'completed':
        mailing_item.mailing_status = 'launched'
    else:
        mailing_item.mailing_status = 'completed'

    mailing_item.save()

    return redirect(reverse('mailing:mailing_detail', args=[mailing_item.pk]))


class LogListView(ListView):
    model = Log

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<body>

<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'mailing:home' %}" class="nav-link px-2 text-white">Главная</a></li>
                <li><a href="{% url 'mailing:mailing_list' %}" class="nav-link px-2 text-white">Рассылки</a></li>
                <li><a href="{% url 'mailing:client_list' %}" class="nav-link px-2 text-white">Клиенты</a></li>
                <li><a href="{% url 'mailing:message_list' %}" class="nav-link px-2 text-white">Сообщения</a></li>
                <li><a href="{% url 'mailing:log_list' %}" class="nav-link px-2 text-white">Отчеты рассылки</a></li>
                {% if user.is_staff %}
                <li><a href="{% url 'users:user_list' %}" class="nav-link px-2 text-white">Список пользователей</a></li>
                {% endif %}
                {% if user.is_content_manager %}
                <li><a href="#" class="nav-link px-2 text-white">Блог</a></li>
                {% endif %}
            </ul>

            <div class="text-end">
                {% if user.is_authenticated %}
                Привет, {{ user.email }}!
                    <a class="btn btn-outline-light me-2" href="{% url 'users:profile' %}">Профиль</a>
                    <a class="btn btn-outline-light me-2" href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a href="{% url 'users:login' %}" type="button" class="btn btn-outline-light me-2">Войти</a>
                    <a href="{% url 'users:register' %}" type="button" class="btn btn-warning">Зарегистрироваться</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

{% block content %}
{% endblock %}

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Удалить клиента</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить клиента "{{ object.name }}"?</p>
            <div class="btn-group">
                <button type="submit"
                        class="btn btn-sm btn-outline-danger">Удалить
                </button>
                <a href="{% url 'mailing:client_list' %}" type="button"
                   class="btn btn-sm btn-outline-secondary">Отмена
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Добавить клиента</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col">
            <div class="card shadow-sm">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                    <div class="card-footer"></div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Клиенты</h1>
                {% if not user.is_authenticated %}
                <p class="lead text-muted">Авторизуйтесь, чтобы начать пользоваться сервисом.</p>
                {% else %}
                <p class="lead text-muted">Нажмите "Добавить клиента" для добавления нового клиента.</p>
                <p>

                    <a href="{% url 'mailing:create_client' %}" class="btn btn-primary my-2">Добавить клиента</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <td>Имя</td>
                                    <td>{{ object.name }}</td>
                                </tr>
                                <tr>
                                    <td>Почта</td>
                                    <td>{{ object.email }}</td>
                                </tr>
                                <tr>
                                    <td>Комментарий</td>
                                    <td>{{ object.comment }}</td>
                                </tr>
                            </table>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    {% if object.creator == request.user%}
                                    <a href="{% url 'mailing:update_client' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Редактировать
                                    </a>
                                    <a href="{% url 'mailing:delete_client' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Удалить
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <td>Статус попытки</td>
                                    <td>{{ object.attempt_status }}</td>
                                </tr>
                                <tr>
                                    <td>Ответ почтового сервера</td>
                                    <td>{{ object.response }}</td>
                                </tr>
                            </table>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="#" type="button"
                                       class="btn btn-sm btn-outline-secondary">Редактировать
                                    </a>
                                    <a href="#" type="button"
                                       class="btn btn-sm btn-outline-danger">Удалить
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Удалить рассылку</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить рассылку "{{ object.pk }}"?</p>
            <div class="btn-group">
                <button type="submit"
                        class="btn btn-sm btn-outline-danger">Удалить
                </button>
                <a href="{% url 'mailing:mailing_list' %}" type="button"
                   class="btn btn-sm btn-outline-secondary">Отмена
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<!-- <section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Рассылка {{ object.pk }}</h1>
        </div>
    </div>
</section> -->
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col">
            <div class="card shadow-sm">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                        Рассылка {{ object.pk }}
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Время рассылки:</td>
                                <td>{{ object.mailing_duration }}</td>
                            </tr>
                            <tr>
                                <td>Периодичность:</td>
                                <td>{{ object.frequency }}</td>
                            </tr>
                            <tr>
                                <td>Статус рассылки:</td>
                                <td>{{ object.mailing_status }}</td>
                            </tr>
                            <tr>
                                <td>Клиенты:</td>
                                <td>
                                    {% for client in object.client.all  %}
                                    <p>{{ client }}</p>
                                    {% endfor %}
                                </td>
                            </tr>
                            <tr>
                                <td>Тема письма:</td>
                                <td>{{ object.message.subject }}</td>
                            </tr>
                            <tr>
                                <td>Тело письма:</td>
                                <td>{{ object.message.body }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div class="btn-group">
                            {% if object.mailing_status == "launched" %}
                            <a href="{% url 'mailing:launch_mailing' object.pk %}"
                               type="button" class="btn btn-outline-danger">
                                Завершить рассылку
                            </a>
                            {% else %}
                            <a href="{% url 'mailing:launch_mailing' object.pk %}"
                               type="button" class="btn btn-outline-success">
                                Запустить рассылку
                            </a>
                            {% endif %}
                            {% if object.creator == request.user%}
                            <a href="{% url 'mailing:update_mailing' object.pk %}" type="button"
                               class="btn btn-outline-primary">Редактировать
                            </a>
                            <a href="{% url 'mailing:delete_mailing' object.pk %}" type="button"
                               class="btn btn-outline-danger">Удалить
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Рассылки</h1>
                {% if not user.is_authenticated %}
                <p class="lead text-muted">Авторизуйтесь, чтобы начать пользоваться сервисом.</p>
                {% else %}
                <p class="lead text-muted">Нажмите "Создать рассылку" для создания новой рассылки.</p>
                <p>

                    <a href="{% url 'mailing:create_mailing' %}" class="btn btn-primary my-2">Создать рассылку</a>
                    {% endif %}
                </p>
            </div>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <td>Рассылка</td>
                                    <td>{{ object.pk }}</td>
                                </tr>
                                <tr>
                                    <td>Сообщение</td>
                                    <td>{{ object.message.body }}</td>
                                </tr>
                            </table>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{% url 'mailing:mailing_detail' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Открыть
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Сообщения</h1>
                {% if not user.is_authenticated %}
                <p class="lead text-muted">Авторизуйтесь, чтобы начать пользоваться сервисом.</p>
                {% else %}
                <p class="lead text-muted">Нажмите "Создать сообщение" для создания нового сообщения.</p>
                <p>

                    <a href="{% url 'mailing:create_message' %}" class="btn btn-primary my-2">Создать сообщение</a>
                </p>
                {% endif %}
            </div>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <td>Тема</td>
                                    <td>{{ object.subject }}</td>
                                </tr>
                                <tr>
                                    <td>Сообщение</td>
                                    <td>{{ object.body }}</td>
                                </tr>
                            </table>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    {% if object.creator == request.user%}
                                    <a href="{% url 'mailing:update_message' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Редактировать
                                    </a>
                                    <a href="{% url 'mailing:delete_message' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Удалить
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}