blog/urls.py
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, AuthView, ProfileView, EmailVerify, generate_new_password, UserListView, \
    toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('', AuthView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    is_content_manager = models.BooleanField(default=False, verbose_name='контент-менеджер')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2',)


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserAuthenticationForm(StyleFormMixin, AuthenticationForm):
    model = User

users/views.py
import random

from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import HttpRequest
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm, UserAuthenticationForm
from users.models import User
from users.services import send_verify_email_message


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verify')

    def form_valid(self, form):
        user: User = form.save()
        send_verify_email_message(verification_url=self.get_verify_email_url(user), recipient_email=user.email)
        messages.info(self.request, 'Подтвердите почту, чтобы завершить регистрацию')
        return redirect('users:login')

    def get_verify_email_url(self, user) -> str:
        current_site = get_current_site(self.request)
        domain = current_site.domain
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)
        url_path = reverse('users:verify_email', kwargs={'uidb64': uid, 'token': token})
        return f'http://{domain}{url_path}'


class EmailVerify(View):
    def get(self, request: HttpRequest, uidb64: str, token: str):
        user = self.get_user(uidb64)
        if not user or not default_token_generator.check_token(user, token):
            messages.warning(self.request, 'Invalid reset link, please try to get it again')
        else:
            messages.success(self.request, 'Email successfully confirmed')
            user.is_active = True
            user.save()
        return redirect('users:login')

    def get_user(self, uid_base64: str) -> User | None:
        try:
            uid = urlsafe_base64_decode(uid_base64).decode()
            user_id = int(uid)
            user = User.objects.get(pk=user_id)
        except (ValueError, User.DoesNotExist):
            user = None
        return user


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class AuthView(LoginView):
    model = User
    form_class = UserAuthenticationForm


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])

    send_mail(
        "Смена пароля",
        f"Ваш новый пароль: {new_password}",
        settings.EMAIL_HOST_USER,
        [request.user.email],
        fail_silently=False,
    )

    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('users:login'))


class UserListView(ListView):
    model = User


def toggle_activity(request, pk):
    student_item = get_object_or_404(User, pk=pk)

    if student_item.is_active:
        student_item.is_active = False
    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse('users:user_list'))

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Вход</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col">
            <div class="card shadow-sm">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Войти</button>
                        </form>
                    </div>
                    <div class="card-footer"></div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Регистрация</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col">
            <div class="card shadow-sm">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                        </form>
                    </div>
                    <div class="card-footer"></div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Регистрация</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col">
            <div class="card shadow-sm">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </form>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-outline-primary" href="{% url 'users:generate_new_password' %}">Сгенерировать пароль</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Список пользователей сервиса</h1>
            </div>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <table class="table">
                                    <tr>
                                        <td>Почта</td>
                                        <td>{{ object.email }}</td>
                                    </tr>
                                    <tr>
                                        <td>Имя</td>
                                        <td>{{ object.first_name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Фамилия</td>
                                        <td>{{ object.last_name }}</td>
                                    </tr>
                                </table>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        {% if object.is_active %}
                                            <a href="{% url 'users:toggle_activity' object.pk %}" type="button"
                                               class="btn btn-sm btn-outline-danger">Блокировать пользователя
                                            </a>
                                        {% else %}
                                            <a href="{% url 'users:toggle_activity' object.pk %}" type="button"
                                               class="btn btn-sm btn-outline-success">Активировать пользователя
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}